version: '3'
services:
  mysql:
    image: biarms/mysql:5.7
    container_name: mysqldb_nest101
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - server-net

  redis:
    image: redis
    container_name: redis_nest101
    ports:
      - "6379:6379"
    networks:
      - server-net

  mongo:
    image: mongo
    container_name: mongo_nest101
    ports:
      - "27017:27017"
    networks:
      - server-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express_nest101
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: false
    networks:
      - server-net

volumes:
  mysql-data:
  redis-data:
  mongo-data:
networks:
  server-net:
